   services:
     mongodb:
       image: mongo:latest
       container_name: mongodb
       ports:
         - "27017:27017"
       environment:
         MONG_USERNAME: user
         MONGO_PASSWORD: user
       volumes:
         - mongo-data:/data/db

   volumes:
     mongo-data: