name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint for linting
      - name: Run ESLint
        run: npm run lint

      # Run Prettier for formatting
      - name: Run Prettier
        run: npm run format